import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";


import { ThemeProvider as NextThemesProvider } from 'next-themes';
import { Toaster } from "react-hot-toast";


const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Doweit",
  description: "Generated by Doweit",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      {/* <GoogleOneTap /> */}
      <html lang="en">

        <body className={inter.className}>
          <NextThemesProvider attribute="class" defaultTheme="light" enableSystem>
            <Toaster position="top-right" />
            {children}

          </NextThemesProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
